### ISSUE TITLE
What is the 'fu' meaning in the name of this project

### ISSUE THREAD

**Issue by APIPLM** [Wilfred/elisp-fu#1]
I just talked with irek, who is in the Emacs channel. He/she made a joke about the martial art. LIke Kung-fu, then have a name of elisp-fu.
Then searched on bing.com, found out your project. I  am curious about the name of this project elisp-fu, the 'fu' means Kung-fu?

**Comment by Wilfred** [comment]
Yeah, skill in usage, much like https://en.wiktionary.org/wiki/Google-fu
